### ISSUE TITLE
"earcut" function missing

### ISSUE THREAD

**Issue by mflux** [citybound/comp-geo#1]
Hi @aeickhoff I'm trying to port over your comp geo for my own purposes. I've gotten the skeleton built but the way to triangulate that is still a mystery. It looks like there's some missing stuff in shape.js where it's referring to "earcut" however that's not in any of the repositories. Although, I'm not even sure if you're using that to triangulate a skeleton either.

Anyhow, if you have more of your old JS code I would love to see them as reference. Good luck on CB rust version!

**Comment by aeplay** [comment]
I believe earcut came from a dependency, let me check that...

**Comment by mflux** [comment]
Could it be from https://github.com/mapbox/earcut

**Comment by aeplay** [comment]
Yes, I'm pretty sure that was it!

**Comment by mflux** [comment]
Thanks for the quick response! Do you happen to have the solution for triangulating the straight skeleton anywhere? Appreciate posting this archived work.

**Comment by aeplay** [comment]
I never attempted that, but it seems pretty straightforward to do once you have the skeleton.
