### ISSUE TITLE
Fork

### ISSUE THREAD

**Issue by mflux** [citybound/comp-geo#2]
Hi @aeickhoff, I'm wrapping up my forked version of this module. You can check it out here:

https://github.com/mflux/comp-geo

I've made several improvements, fixes, and corrections

- Included missing dependencies: codebuilder, iteratorers, meta-eval, nd-linalg, etc...
- Replaced missing dependencies like kinda-random with chance.js
- Fixed all of the non-working roughlyEqual / roughlyBetween and relevant assertions
- Fixed all of the out of date path last vertex fetching
- Rewrote triangulation to work with cdt2d instead of earcut
- Wrote a new webgl example that outputs three.js mesh

All of the skeleton and primitives tests pass. I wasn't able to get clipper or intersections tests passing.

It would be great to A. get your blessing on passing this work forward in the fork and B. OK the amendment to the license which I modified. Seeing as to how the JS comp-geo is no longer maintained and it's a net benefit to the webgl community to have this really nice straight-skeleton implementation for them to use.

Let me know how you prefer to do things!

**Comment by mflux** [comment]
![screenshot 2017-04-19 17 06 57](https://cloud.githubusercontent.com/assets/1041360/25208817/eac52730-252b-11e7-981a-85fa98b0321b.png)
![screenshot 2017-04-19 17 06 52](https://cloud.githubusercontent.com/assets/1041360/25208819/ed57a464-252b-11e7-9687-508f8e92e4e2.png)

Triangulation :)

**Comment by aeplay** [comment]
I'm okay with the fork and the license amendment! Really cool to see this being useful to someone, even producing visual output!
